import { BaseEntity } from '../../common/baseentity';

export class Uniquelinktableforadaptivemodulation extends BaseEntity {

	vendor: string;
	source_ne_name: string;
	source_board: string;
	source_port: string;
	source_card_name: string;
	sink_ne_name: string;
	sink_board: string;
	sink_port: string;
	sink_card_name: string;
	source_protect_type: string;
	source_protection_group_id: string;
	source_xpic_group_id: string;
	source_xpic_group_capacity: string;
	source_ne_frequency: string;
	sink_ne_frequency: string;
	source_ne_radio_work_mode: string;
	packet_link_capacity: string;
	max_capacity: string;
	max_modulation: string;
	link_code_a_end: string;
	link_code_z_end: string;
	system_link_code: string;
	link_code_combination: string;
	ldma_link_id: string;
	system_link_code_main: string;
	system_link_code_protection: string;
	dataForDate: Date;
	qam4: number;
	qam8: number;
	qam16: number;
	qam32: number;
	qam64: number;
	qam128: number;
	qam256: number;
	qam512: number;
	qam1024: number;
	qam2048: number;
	qam4096: number;
	otherqam4: number;
	otherqam8: number;
	otherqam16: number;
	otherqam32: number;
	otherqam64: number;
	otherqam128: number;
	otherqam256: number;
	otherqam512: number;
	otherqam1024: number;
	otherqam2048: number;
	otherqam4096: number;
	finalqam4: number;
	finalqam8: number;
	finalqam16: number;
	finalqam32: number;
	finalqam64: number;
	finalqam128: number;
	finalqam256: number;
	finalqam512: number;
	finalqam1024: number;
	finalqam2048: number;
	finalqam4096: number;
	commercialZone: string;
	division: string;
	district: string;
	thana: string;
	unionName: string;
	pmfZone: string;
	uploadedAttachment: string;
	uploadedAttachmentFileId: string;
	downloadAttachment: string;
	remarks: string;
	maxModulation: string;
	maxModulationTime : number;

}
