// @author Jewel Rana
// @this component is auto generated by code generator
// @version V1
// @date 6th August 2020

import { Injectable } from "@angular/core";
import { Observable, of } from "rxjs";

import { Constants } from "../../common";
import { Sampledashboard } from "../dto/sampledashboard";
import { ApiResponse } from "../../common/apiresponse";
import { HttpbaseService } from "../../common/httpbase.service";

const uri = Constants.apiUrl + "/sampledashboard/post";

@Injectable({
  providedIn: "root",
})
export class SampledashboardService {
  constructor(private httpbase: HttpbaseService) {}

  getSampledashboardList(): Observable<ApiResponse> {
    return this.httpbase.getEntityList(uri);
  }

  getSampledashboardById(id): Observable<ApiResponse> {
    return this.httpbase.getEntityById(uri, id);
  }

  saveSampledashboard(
    sampledashboard: Sampledashboard
  ): Observable<ApiResponse> {
    return this.httpbase.saveEntity(uri, sampledashboard);
  }

  deleteSampledashboard(
    sampledashboard: Sampledashboard
  ): Observable<ApiResponse> {
    return this.httpbase.deleteEntity(uri, sampledashboard);
  }
}
