// @author Jewel Rana
// @this component is auto generated by code generator
// @version V1
// @date 6th August 2020

import { BaseEntity } from '../../common/baseentity';

export class Sampledashboard extends BaseEntity {

	officeId: number;
	officeName: string;
	officeType: string;
	address: string;
	longitude: string;
	latitude: string;
	assetType: string;
	remarks: string;


}
